#!/bin/bash

#HEADERS VARIABLES
ALGORITHM="RS256"
TYPE="JWT"
KEY_ID="FIREBASE_KEY_ID"

#PAYLOAD VARIABLES
ISSUE_TIME=$(date '+%s')
EXPIRATION_TIME=$(( $(date '+%s') + 3600 ))
AUDIENCE="https://oauth2.googleapis.com/token"

#DEPENDENT VARIABLES
FIREBASE_SERVICE_ACCOUNT_EMAIL="YOUR_FIREBASE_EMAIL_ADDRESS"
FIREBASE_SCOPE="FIREBASE_SCOPE"
SERVICE_ACCOUNT_KEY_FILE="PATH_TO_YOUR_JSON"
SERVICE_ACCOUNT_PRIVATE_KEY_PEM="/tmp/service-account-key.pem"


#Extract private key from JSON and save it to a PEM file
#Uncomment to choose preferred tool between awk, sed and jq to extract the value.
# jq -r '.private_key' "$SERVICE_ACCOUNT_KEY_FILE" > "$SERVICE_ACCOUNT_PRIVATE_KEY_PEM"
grep -o '"private_key":\s*"[^"]*"' "$SERVICE_ACCOUNT_KEY_FILE" | awk -F'"' '{gsub(/\\n/, "\n", $4); gsub(/\\/, "", $4); print $4}' | tr -d '\\"' > "$SERVICE_ACCOUNT_PRIVATE_KEY_PEM"
# grep -o '"private_key":\s*"[^"]*"' "$SERVICE_ACCOUNT_KEY_FILE" | sed 's/"private_key":\s*"//' | sed 's/\"//g' | sed 's/\\n/\'$'\n/g' > "$SERVICE_ACCOUNT_PRIVATE_KEY_PEM"

header='{"alg":"RS256","typ":"JWT"}'
payload="{\"iss\":\"$FIREBASE_SERVICE_ACCOUNT_EMAIL\",\"scope\":\"$FIREBASE_SCOPE\",\"aud\":\"$AUDIENCE\",\"iat\":$ISSUE_TIME,\"exp\":$EXPIRATION_TIME}"
base64_header=$(echo -n "$header" | openssl base64 | tr -d '=' | tr '/+' '_-' | tr -d '\n')
base64_payload=$(echo -n "$payload" | openssl base64 | tr -d '=' | tr '/+' '_-' | tr -d '\n')
header_payload="${base64_header}.${base64_payload}"
signature=$(echo -n "$header_payload" | openssl dgst -sha256 -sign "$SERVICE_ACCOUNT_KEY_PEM" | openssl base64 | tr -d '=' | tr '/+' '_-' | tr -d '\n')
jwt_token="${header_payload}.${signature}"
echo "$jwt_token" && rm "$SERVICE_ACCOUNT_KEY_PEM"

